module.exports = {
    ark: {
        list: [
            'arkstone',
            'dodo-blue',
            'dodo-cyan',
            'dodo-default',
            'dodo-lime',
            'dodo-red',
            'dodo-yellow',
            'mushroom',
            'woodsign',
        ],
        type: 'author_flair_css_class',
    },
    battlefield1: {
        list: [
            'xbox',
            'origin',
            'psn',
        ],
        type: 'author_flair_css_class',
    },
    csgo: {
        list: [
            '/r/globaloffensive janitor',
            '/r/globaloffensive moderator',
            '/r/globaloffensive monsorator',
            '3dmax fan',
            '400k hype',
            '5 year subreddit veteran',
            'astana dragons fan',
            'astralis fan',
            'baggage veteran',
            'banner competition #1 winner',
            'banner competition #2 first place winner',
            'banner competition #2 second place winner',
            'banner competition #2 third place winner',
            'bloodhound',
            'bravado gaming fan',
            'bravo',
            'cache veteran',
            'cheeky moderator',
            'chroma',
            'clan-mystik fan',
            'cloud9 fan',
            'cloud9 g2a fan',
            'cobblestone veteran',
            'complexity fan',
            'copenhagen wolves fan',
            'counter logic gaming fan',
            'dat team fan',
            'dust 2 veteran',
            'envyus fan',
            'epsilon esports fan',
            'esc gaming fan',
            'extra life tournament caster',
            'extra life tournament finalist',
            'faze clan fan',
            'flipsid3 tactics fan',
            'flipside tactics fan',
            'fnatic fan',
            'fnatic fanatic',
            'g2 esports fan',
            'gambit gaming fan',
            'gamers2 fan',
            'godsent fan',
            'guardian 2',
            'guardian elite',
            'guardian',
            'hellraisers fan',
            'ibuypower fan',
            'inferno veteran',
            'italy veteran',
            'keyd stars fan',
            'kinguin fan',
            'ldlc fan',
            'legendary chicken master',
            'legendary lobster master',
            'lgb esports fan',
            'london consipracy fan',
            'london conspiracy fan',
            'luminosity gaming fan',
            'militia veteran',
            'mirage veteran',
            'moderator',
            'mousesports fan',
            'myxmg fan',
            'n!faculty fan',
            'natus vincere fan',
            'ninjas in pyjamas fan',
            'north fan',
            'nuke vetera',
            'nuke veteran',
            'office veteran',
            'official dunkmaster',
            'one bot to rule them all',
            'optic gaming fan',
            'overpass veteran',
            'penta esports fan',
            'penta sports fan',
            'phoenix',
            'planetkey dynamics fan',
            'reason gaming fan',
            'recursive fan',
            'renegades fan',
            'sk gaming fan',
            'splyce fan',
            'tactics',
            'team astralis fan',
            'team dignitas fan',
            'team ebettle fan',
            'team envyus fan',
            'team immunity fan',
            'team kinguin fan',
            'team liquid fan',
            'team solomid fan',
            'team wolf fan',
            'titan fan',
            'train veteran',
            'trial moderator',
            'tsm kinguin fan',
            'universal soldiers fan',
            'valeria',
            'verygames fan',
            'vexed gaming fan',
            'victory',
            'virtus pro fan',
            'virtus.pro fan',
            'vox eminor fan',
            'xapso fan',
        ],
        type: 'author_flair_text',
    },
    elite: {
        list: [
            'bot img',
            'cmdr img alliance',
            'cmdr img cobra',
            'cmdr img empire',
            'cmdr img federation',
            'cmdr img sidey',
            'cmdr img skull',
            'cmdr img viper',
            'cmdr',
            'harmless cmdr',
            'img viper cmdr',
            'mostlyharmless cmdr',
            'star',
        ],
        type: 'author_flair_css_class',
    },
    rainbow6: {
        list: [
            'ash',
            'ashnew',
            'bandit',
            'banditnew',
            'blackbeard',
            'blackbeardnew',
            'blitz',
            'blitznew',
            'buck',
            'bucknew',
            'capitao',
            'capitaonew',
            'castle',
            'castlenew',
            'caveira',
            'caveiranew',
            'doc',
            'docnew',
            'frost',
            'frostnew',
            'fuze',
            'fuzenew',
            'glaz',
            'glaznew',
            'iq',
            'iqnew',
            'jager',
            'jagernew',
            'kapkan',
            'kapkannew',
            'mod',
            'montagne',
            'montagnenew',
            'mute',
            'mutenew',
            'pulse',
            'pulsenew',
            'recruit',
            'rook',
            'rooknew',
            'sledge',
            'sledgenew',
            'smoke',
            'smokenew',
            'tachanka',
            'tachankanew',
            'thatcher',
            'thatchernew',
            'thermite',
            'thermitenew',
            'twitch',
            'twitchnew',
            'valkyrie',
            'valkyrienew',
        ],
        type: 'author_flair_css_class',
    },
    rimworld: {
        list: [
            'fun',
            'gold',
            'granite',
            'jade',
            'limestone',
            'marble',
            'mod',
            'plasteel',
            'sandstone',
            'mod2',
            'silver',
            'slate',
            'steel',
            'uranium',
            'war',
            'wood',
        ],
        type: 'author_flair_css_class',
    },
};
