const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        'bacon bits on the surface of my mind',
        'lpc',
        'lps',
        'lxb',
        'pc1',
        'pc2',
        'pc3',
        'pc4',
        'pccol',
        'pcint',
        'pcrngr',
        'pcstr',
        'pcstr',
        'ps1',
        'ps2',
        'ps3',
        'ps4',
        'pscol',
        'psint',
        'psrngr',
        'psstr',
        'xb1',
        'xb2',
        'xb3',
        'xb4',
        'xbcol',
        'xbint',
        'xbrngr',
        'xbstr',
    ],
    type: 'author_flair_css_class',
} );
