module.exports = {
    getFlairs: function getFlairs () {
        return this.list;
    },
    list: [
        'bot img',
        'cmdr img aduval',
        'cmdr img aegis',
        'cmdr img alduval',
        'cmdr img alliance',
        'cmdr img antal',
        'cmdr img cobra',
        'cmdr img combat',
        'cmdr img coredyn',
        'cmdr img delaine',
        'cmdr img empire',
        'cmdr img explore',
        'cmdr img fdelacy',
        'cmdr img federation',
        'cmdr img galnet',
        'cmdr img grom',
        'cmdr img hudson',
        'cmdr img mahon',
        'cmdr img patreus',
        'cmdr img rescue',
        'cmdr img sidey',
        'cmdr img skull',
        'cmdr img snoo',
        'cmdr img thargint',
        'cmdr img thargsen',
        'cmdr img trade',
        'cmdr img viper',
        'cmdr img winters',
        'cmdr img yongrui',
        'cmdr img zorgpet',
        'cmdr star',
        'cmdr',
        'competent cmdr',
        'dangerous cmdr',
        'elite1 cmdr',
        'empire cmdr img',
        'empire',
        'harmless cmdr',
        'img sidey cmdr',
        'img viper cmdr',
        'mostlyharmless cmdr',
        'novice cmdr',
        'star',
    ],
    type: 'author_flair_css_class',
};
