const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        '74m',
        '74n',
        'ak',
        'akms',
        'aksu',
        'apb',
        'class-mod',
        'dvl',
        'flair-ballisticsexpert',
        'flair-contentcreator',
        'flair-css',
        'flair-discord',
        'flair-emissary',
        'flair-forummod',
        'flair-map',
        'flair-mod',
        'flair-pixel',
        'flair-rainbow',
        'flair-tlead',
        'flair-twitch',
        'flair-youtube',
        'fort',
        'glock',
        'iotv',
        'kedr',
        'm1a',
        'm4',
        'm870',
        'mak',
        'mosin',
        'mp153',
        'mp5',
        'mpx',
        'mr133',
        'pp19',
        'rsass',
        'sa58',
        'saiga12',
        'sks',
        'sv98',
        'toz',
        'tsks',
        'tt',
        'val',
        'vepr',
        'vss',
    ],
    type: 'author_flair_css_class',
} );
