const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        'ak',
        'aksu',
        'class-mod',
        'dvl',
        'flair-contentcreator',
        'flair-css',
        'flair-discord',
        'flair-emissary',
        'flair-forummod',
        'flair-map',
        'flair-mod',
        'flair-pixel',
        'flair-rainbow',
        'flair-tlead',
        'flair-twitch',
        'flair-youtube',
        'kedr',
        'm4',
        'mak',
        'mp5',
        'mpx',
        'rsass',
        'sks',
        'sv98',
        'toz',
    ],
    type: 'author_flair_css_class',
} );
