module.exports = {
    getFlairs: function getFlairs () {
        return this.list;
    },
    list: [
        'beetlejess',
        'default',
        'dragonsarah',
        'energythief',
        'grenadier',
        'hazardkyle',
        'hero-assassin',
        'hero-centurion',
        'hero-commando',
        'hero-dim-mak',
        'hero-dragon',
        'hero-electro-pulse',
        'hero-hotfixer',
        'hero-megabase',
        'hero-pathfinder',
        'hero-phase-scout',
        'hero-poisoner',
        'hero-power-base',
        'hero-ranger',
        'hero-recon-scout',
        'hero-rescue-trooper',
        'hero-shock-specialist',
        'hero-shock-trooper',
        'hero-shuriken-master',
        'hero-special-forces',
        'hero-support-specialist',
        'hero-survivalist',
        'hero-tank',
        'hero-trailblaster',
        'hero-trailblazer',
        'hero-urban-assault',
        'hero-vanguard',
        'hero-warlord',
        'lama1',
        'llama',
        'llamamaster',
        'machinist',
        'marinecorpse',
        'ninja1',
        'raider',
        'shurikenmasternew',
        'skullshot',
        'soldier2',
    ],
    type: 'author_flair_css_class',
};
