const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        '/r/globaloffensive janitor',
        '/r/globaloffensive moderator',
        '/r/globaloffensive monsorator',
        '#r/globaloffensive admin',
        '3dmax fan',
        '400k hype',
        '5 year subreddit veteran',
        'astana dragons fan',
        'astralis fan',
        'baggage veteran',
        'banner competition #1 &amp; #3 winner',
        'banner competition #1 winner',
        'banner competition #2 first place winner',
        'banner competition #2 second place winner',
        'banner competition #2 third place winner',
        'banner competition #3 fifth place',
        'banner competition #3 fourth place',
        'banner competition #3 second place',
        'banner competition #3 third place',
        'best ever moderator',
        'big fan',
        'bloodhound',
        'bravado gaming fan',
        'bravo',
        'cache veteran',
        'captain moderator',
        'cheeky moderator',
        'chroma',
        'clan-mystik fan',
        'cloud9 fan',
        'cloud9 g2a fan',
        'cobblestone veteran',
        'complexity fan',
        'copenhagen wolves fan',
        'counter logic gaming fan',
        'dat team fan',
        'don\'t make me moderate you',
        'dust 2 veteran',
        'envyus fan',
        'epsilon esports fan',
        'esc gaming fan',
        'extra life tournament caster',
        'extra life tournament finalist',
        'faze clan fan',
        'flipsid3 tactics fan',
        'flipside tactics fan',
        'fnatic fan',
        'fnatic fanatic',
        'g2 esports fan',
        'gambit esports fan',
        'gambit gaming fan',
        'gamers2 fan',
        'genuine 500k party pin',
        'godsent fan',
        'guardian 2',
        'guardian elite',
        'guardian',
        'hellraisers fan',
        'https://youtu.be/hX21XHcdlM4?t=15s',
        'ibuypower fan',
        'ibp fan',
        'immortals fan',
        'inferno veteran',
        'italy veteran',
        'keyd stars fan',
        'kinguin fan',
        'ldlc fan',
        'legendary chicken master',
        'legendary lobster master',
        'lgb esports fan',
        'london consipracy fan',
        'london conspiracy fan',
        'luminosity gaming fan',
        'militia veteran',
        'mirage veteran',
        'modding since 2014',
        'moderator',
        'mousesports fan',
        'myxmg fan',
        'n!faculty fan',
        'natus vincere fan',
        'ninjas in pyjamas fan',
        'north fan',
        'nuke vetera',
        'nuke veteran',
        'office veteran',
        'official dunkmaster',
        'one bot to rule them all',
        'optic gaming fan',
        'overpass veteran',
        'penta esports fan',
        'penta fan',
        'penta sports fan',
        'phoenix',
        'planetkey dynamics fan',
        'possibly robot moderator',
        'r/GlobalOffensive Zookeeper',
        'reason gaming fan',
        'recursive fan',
        'renegades fan',
        'sk gaming fan',
        'splyce fan',
        'tactics',
        'team astralis fan',
        'team dignitas fan',
        'team ebettle fan',
        'team envyus fan',
        'team immunity fan',
        'team kinguin fan',
        'team liquid fan',
        'team solomid fan',
        'team wolf fan',
        'titan fan',
        'top notch moderation or your money back',
        'train veteran',
        'trial moderator',
        'tsm kinguin fan',
        'universal soldiers fan',
        'valeria',
        'vega squadron fan',
        'verygames fan',
        'vexed gaming fan',
        'victory',
        'virtus pro fan',
        'virtus.pro fan',
        'vox eminor fan',
        'worst ever moderator',
        'xapso fan',
    ],
    type: 'author_flair_text',
} );
