const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        'a42-l',
        'a42-n',
        'aaa-l',
        'aaa-n',
        'adrenaline-syringe',
        'ahnf-l',
        'ahnf-n',
        'bandage',
        'bm-l',
        'bm-n',
        'db-l',
        'db-n',
        'discordmod',
        'energy-drink',
        'est-l',
        'est-n',
        'fb-l',
        'fb-n',
        'first-aid',
        'gal-l',
        'gal-n',
        'gpan',
        'gtd-l',
        'gtd-n',
        'hbrc-b',
        'hbrc-g',
        'hbrc-s',
        'igncustom',
        'jerrycan',
        'lpup',
        'lvl1-backpack',
        'lvl1-helmet',
        'lvl1-vest',
        'lvl2-backpack',
        'lvl2-helmet',
        'lvl2-vest',
        'lvl3-backpack',
        'lvl3-helmet',
        'lvl3-vest',
        'medkit',
        'moderator',
        'npan',
        'npup',
        'painkiller',
        'panned',
        'pans',
        'ssoq-l',
        'ssoq-n',
        't20-l',
        't20-n',
        'trophy',
        'u-l',
        'u-n',
        'woof',
    ],
    type: 'author_flair_css_class',
} );
