module.exports = {
    getFlairs: function getFlairs () {
        return this.list;
    },
    list: [
        'a42-l',
        'a42-n',
        'aaa-l',
        'aaa-n',
        'ahnf-l',
        'ahnf-n',
        'bm-l',
        'bm-n',
        'discordmod',
        'est-l',
        'est-n',
        'fb-n',
        'fb-l',
        'gal-l',
        'gal-n',
        'gpan',
        'gtd-l',
        'gtd-n',
        'hbrc-b',
        'hbrc-g',
        'hbrc-s',
        'igncustom',
        'lpup',
        'npan',
        'npup',
        't20-l',
        't20-n',
        'trophy',
        'woof',
    ],
    type: 'author_flair_css_class',
};
