const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        'bestof',
        'community',
        'extralife',
        'frontier',
        'fun',
        'gold',
        'granite',
        'hoarder',
        'jade',
        'limestone',
        'marble',
        'mod',
        'mod2',
        'plasteel',
        'pmfaf',
        'sandstone',
        'ship',
        'silver',
        'slate',
        'steel',
        'suede',
        'uranium',
        'war',
        'west',
        'wood',
    ],
    type: 'author_flair_css_class',
} );
