const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        'alphac', // AlphaConsole
        'aus',
        'bronze1',
        'bronze2',
        'bronze3',
        'can',
        'chall',
        'chall2',
        'chall3',
        'chall4',
        'cham',
        'cham1',
        'cham2',
        'cham3',
        'diamond1',
        'diamond2',
        'diamond3',
        'dutch',
        'eng',
        'fanalsyd', // Alpha Sydney
        'fanc9',
        'fanchief', // Fan Chiefs
        'fancow',
        'fanflip',
        'fang2',
        'fanibp',
        'fankou',
        'fanmeth',
        'fanmock', // Fan Mock-It
        'fannor',
        'fannv',
        'fanpock',
        'fanpsg',
        'fanrog',
        'fantsec', // Fan Team Secret
        'flyquest',
        'france',
        'gale',
        'gc',
        'gccca', // College Carball Association
        'gccow',
        'gold1',
        'gold2',
        'gold3',
        'grandegg',
        'mld',
        'mod2',
        'plat1',
        'plat2',
        'plat3',
        'prosp',
        'prosp2',
        'prosp4',
        'psn',
        'rlcs', // Rocket League Championship Series
        'rlesports', // /r/RocketLeagueEsports Moderator
        'rlrs', // Maybe re-add in the future. Not a proper dev tho
        'scot',
        'silentecho',
        'silver1',
        'silver2',
        'silver3',
        'smashgg', // Maybe re-add in the future? No dev tho...
        'star',
        'star1',
        'star2',
        'star3',
        'star4',
        'steam',
        'swe',
        'twitch',
        'unrank',
        'usa',
        'xbox',
    ],
    type: 'author_flair_css_class',
} );
