const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        'aus',
        'bronze1',
        'bronze2',
        'bronze3',
        'can',
        'chall',
        'chall2',
        'chall3',
        'chall4',
        'cham',
        'cham1',
        'cham2',
        'cham3',
        'diamond1',
        'diamond2',
        'diamond3',
        'dutch',
        'eng',
        'fanc9',
        'fanflip',
        'fang2',
        'fanibp',
        'fankou',
        'fanmeth',
        'fannv',
        'fanpock',
        'fanpsg',
        'fanrog',
        'france',
        'gc',
        'gccca', // College Carball Association
        'gccow',
        'gold1',
        'gold2',
        'gold3',
        'mod2',
        'plat1',
        'plat2',
        'plat3',
        'prosp',
        'prosp4',
        'rlcs', // Rocket LEague Championship Series
        'rlrs', // Maybe re-add in the future. Not a proper dev tho
        'scot',
        'silver1',
        'silver2',
        'silver3',
        'smashgg', // Maybe re-add in the future? No dev tho...
        'star',
        'star1',
        'star2',
        'star3',
        'star4',
        'steam',
        'swe',
        'twitch',
        'unrank',
        'usa',
        'xbox',
    ],
    type: 'author_flair_css_class',
} );
