const base = require( './base.js' );

module.exports = Object.assign( {}, base, {
    list: [
        '300',
        '300i',
        'aegis',
        'anvil',
        'aurora',
        'avacado',
        'avenger',
        'ayy',
        'banu',
        'bbangry',
        'bbcreep',
        'bbhappy',
        'bbsad',
        'bbsuprised',
        'bbyelling',
        'bishop',
        'bmm',
        'carrack',
        'classicoutlaw',
        'connie',
        'cutlass',
        'defender',
        'dragonfly',
        'drake',
        'freelancer',
        'genericgoofy',
        'herald',
        'herald2',
        'hornet',
        'm50',
        'misc',
        'mustang',
        'nomad',
        'oldman',
        'onionknight',
        'onionknight2',
        'org1',
        'org10',
        'org2',
        'org3',
        'org4',
        'org5',
        'org6',
        'org7',
        'org8',
        'org9',
        'origin',
        'outland',
        'outlaw1',
        'razor',
        'reliant',
        'rsi',
        'sabre',
        'sabre2',
        'scout',
        'scythe',
        'soldier1',
        'tumbril',
        'twitch',
        'worm',
        'youtube',
    ],
    type: 'author_flair_css_class',
} );
