module.exports = {
    getFlairs: function getFlairs () {
        return this.list;
    },
    list: [
        '300i',
        'aegis',
        'anvil',
        'aurora',
        'avacado',
        'avenger',
        'banu',
        'bbangry',
        'bbcreep',
        'bbhappy',
        'bbsad',
        'bbsuprised',
        'bbyelling',
        'bishop',
        'bmm',
        'carrack',
        'classicoutlaw',
        'defender',
        'dragonfly',
        'drake',
        'freelancer',
        'genericgoofy',
        'herald',
        'herald2',
        'hornet',
        'm50',
        'misc',
        'nomad',
        'oldman',
        'onionknight',
        'onionknight2',
        'org1',
        'org9',
        'origin',
        'outland',
        'outlaw1',
        'razor',
        'reliant',
        'rsi',
        'sabre',
        'sabre2',
        'scout',
        'scythe',
        'soldier1',
        'tumbril',
        'twitch',
        'worm',
        'youtube',
    ],
    type: 'author_flair_css_class',
};
